### UPDATE existing patient
PUT http://locahost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "John@example.com",
  "address": "123 main st",
  "dateOfBirth": "1995-09-09"
}

###